services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: project-task-sql
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:latest
    container_name: project-task-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-task-api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ProjectTaskManagementDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
      Redis__ConnectionString: "redis:6379"